version: "3.1"
 
services:

    prometheus:
        build: prom
        image: prometheus
        ports:
            - "9090:9090"
        networks:
            - monitoring
        logging:
          driver: gelf
          options:
            gelf-address: udp://127.0.0.1:12201
            
    node-exporter:
        image: prom/node-exporter:master
        command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points '^/(sys|proc|dev|host|etc)($$|/)' --collector.textfile.directory /etc/node-exporter/ --collectors.enabled='conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs'
        volumes:
            - "/proc:/host/proc"
            - "/sys:/host/sys"
            - "/:/rootfs"
            - "/etc/hostname:/etc/host_hostname"
        environment:
            - HOST_HOSTNAME=/etc/host_hostname
        networks:
            - monitoring
        logging:
          driver: gelf
          options:
            gelf-address: udp://127.0.0.1:12201
        deploy:
            mode: global         

    cadvisor:
        image: google/cadvisor:canary
        volumes:
            - "/:/rootfs"
            - "/var/run:/var/run"
            - "/sys:/sys"
            - "/var/lib/docker:/var/lib/docker"
        networks:
            - monitoring
        logging:
          driver: gelf
          options:
            gelf-address: udp://127.0.0.1:12201
        deploy:
            mode: global
      
networks:
    monitoring:
