version: "3.6"

services:

    prometheus:
        image: quay.io/prometheus/prometheus
#        ports:
#            - 9090:9090
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus:/prometheus
        networks:
            - monitoring

    node-exporter:
        image: quay.io/prometheus/node-exporter
        command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points '^/(sys|proc|dev|host|etc)($$|/)'
        volumes:
            - "/proc:/host/proc"
            - "/sys:/host/sys"
            - "/:/rootfs"
            - "/etc/hostname:/etc/host_hostname"
        environment:
            - HOST_HOSTNAME=/etc/host_hostname
        networks:
            - monitoring
        deploy:
            mode: global

    cadvisor:
        image: google/cadvisor
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run"
            - "/sys:/sys:ro"
            - "/var/lib/docker:/var/lib/docker:ro"
        networks:
            - monitoring
        deploy:
            mode: global

    grafana:
        image: grafana/grafana
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - 3000:3000
        networks:
            - monitoring

networks:
    monitoring:

volumes:
    prometheus:
    grafana_data:
